### PR TITLE
Allow return-path header to be set

### PR DESCRIPTION
**Pull request by pvonpetrin**
Useful for handling auto-replies.

### CODE REVIEW

**Comment by demoore** [comment]
Hey @pvonpetrin did you test this? It looks like this just sets a "Return-Path" header in the request made to Sendwithus' API and Sendwithus would just drop the header.

Your ESP should be handling the return-path header automatically so it can handle bounces.

**Comment by pvonpetrin** [comment]
Ah, you are correct - I should be passing the headers to the api, not the request.

The desire here is to be able to override this header setting on a case-by-case basis, as we need to change the return-path on only some emails. ( this is actually the example you use in the docs, even: https://support.sendwithus.com/delivery/custom_headers/ )

I will fix this request today or Monday.

**Comment by demoore** [comment]
Sounds good 👍  I'd be happy to merge it in.

**Comment by pvonpetrin** [comment]
After doing more testing, it appears that the feature I want is already supported, just not obvious.  Closing this out.

**Comment by demoore** [comment]
Good point! I'm going to document that 😺

**Pull request closed without merging**
