### PR TITLE
Have the batch method return a value besides null on success.

### PR DESCRIPTION
**Pull request by Jason-Rev**
### execute()
- Make the return value consistent with the API.

### cancel()
- Added a cancel function to clear the batched api requests.

### CODE REVIEW

**Comment by Jason-Rev** [comment]
If you change the Travis-CI Settings to limit the number of concurrent jobs to 1, all the tests will work.

Limit Current Jobs

**Comment by demoore** [comment]
Hey @Jason-Rev we'll check this out next week. Are you able to update the readme was well? Thanks! :smile_cat:

**Comment by brandonb927** [comment]
@demoore @Jason-Rev everything looks good here!

**Comment by Jason-Rev** [comment]
Yes, I'll add docs to the readme.

**Comment by brandonb927** [comment]
@Jason-Rev this PR looks good , thanks for the README update. I'll merge it in now!

**Comment by Jason-Rev** [comment]
Thank you!

**Pull request merged**
