### PR TITLE
Implement resend API

### PR DESCRIPTION
**Pull request by buschjost**
Add ability to resend mails based on given log_id.

### CODE REVIEW

**Comment by FlipCodes** [comment]
Thanks for submitting this @buschjost! We'll have our team take a look at this sometime this week.

**Comment by FlipCodes** [comment]
@buschjost Are you able to add an additional test case where this would fail. Otherwise, everything looks great! :) 
Once we have the extra test case, I can merge it in.

**Comment by buschjost** [comment]
I have added the test

**Comment by FlipCodes** [comment]
Thanks @buschjost!

**Pull request merged**
