### PR TITLE
Ports BathAPI from Python client

### PR DESCRIPTION
**Pull request by pbu88**
Hi,

We needed to use you batch api from our client in php and realised that it wasn't implemented there. I could find that it is implemented in your python client so I did a shameless port from the python client to the php client :)

I'm filling this pull request since maybe you find it useful to add it to your php client (and we would love that since then we won't need to extend your code in our codebase but just update from composer instead and thats it :) )

Please let me know your thoughts and if there is some cleaning/fixing that needs to be done before be able to merge it!

Cheers

### CODE REVIEW

**Comment by demoore** [comment]
Hey @pbu88, this looks great! Any PR we get with tests is awesome :smiley: 

It's going to take a couple more days for someone on our team to properly review it, but we'll get it in there.

**Comment by pbu88** [comment]
Awesome! Let me know if I need to improve it further :) I added some comments to the new main public functions (`start_batch` and `execute`)

**Comment by moxuz** [comment]
Thanks a lot @pbu88 
I've merged it and you should be good to go!

**Comment by pbu88** [comment]
You're welcome. Quick question: Why do you discourage batch of >10 requests? We are trying to improve the performance of our email system and though 10x is alright, we were wondering why couldn't it be more?

Thanks!

**Comment by moxuz** [comment]
It's mainly just for performance reasons. If you want to ensure maximum reliability, it's best to keep it to <=10 per batch. We want to give you the best experience we can!

**Pull request merged**
