### PR TITLE
Provide encoded files

### PR DESCRIPTION
**Pull request by dmitry-vinogradov**
Added possibility to provide already base64 encoded files to the API.

### CODE REVIEW

**Comment by demoore** [comment]
Thanks for this @dmitry-vinogradov! We'll evaluate this sometime this week.😸

**Comment by demoore** [comment]
@dmitry-vinogradov this looks great! Thanks for adding a test 😸 

Can you add an example in the README? Then I'll merge it in.

**Comment by dmitry-vinogradov** [comment]
Added description and example usage in README.md

**Comment by demoore** [comment]
Thanks @dmitry-vinogradov!

**Pull request merged**
